name: CI/CD

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Set up Chromedriver for e2e
      uses: nanasess/setup-chromedriver@v1
    - name: Install Dependencies
      run: |
        pip install pipenv
        pipenv install --dev
    - name: Run Tests
      run: |
        pipenv run python manage.py test
        pipenv run python manage.py collectstatic --noinput
        pipenv run python manage.py behave
    - name: Build, Push and Deploy to Heroku
      if: ${{ github.event_name == 'push' }}
      uses: jctaveras/heroku-deploy@v2.1.3
      with:
        email: ${{ secrets.HEROKU_EMAIL }}
        api_key: ${{ secrets.HEROKU_API_KEY }}
        app_name: 'myrecommendations'
        dockerfile_path: ''